#ifndef DOVECOT_VERSION_H
#define DOVECOT_VERSION_H

#define DOVECOT_REVISION "b3ad6004dc"
#define DOVECOT_VERSION_FULL VERSION" ("DOVECOT_REVISION")"
#define DOVECOT_BUILD_INFO DOVECOT_VERSION_FULL

#endif /* DOVECOT_VERSION_H */
