#!/bin/sh
set -e


if [ "$1" = "remove" ]; then
	# Remove the pop3 and pop3s option from the protocols line
	sed -i -e '/^[[:space:]]*protocols *=/ {s/pop3s\?[[:space:]]*//g; s/=[[:space:]]*$/= none/}' \
		/etc/dovecot/protocols.conf
fi

# Restart dovecot because we've updated the configuration file.
if [ -x "/etc/init.d/dovecot" ]; then
	if [ -x /usr/sbin/invoke-rc.d ] ; then
		invoke-rc.d dovecot start
	else
		/etc/init.d/dovecot start
	fi
fi

#DEBHELPER#
