.\"                                      Hey, EMACS: -*- nroff -*-
.TH "DOVECOTPW" "1" "6 November 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
dovecotpw \- a tool to easily generate passwords for a specified password scheme. 
.SH SYNOPSIS
\fBdovecotpw\fP [-l] [-p <password>] [-s <scheme>] [-u <user>] [-V]
.br
.SH DESCRIPTION
\fBdovecotpw\fP is a small tool to easily generate passwords for a
specified password scheme known by  \fIdovecot\fR\|(1).  A password scheme means
the format in which any password is stored in password databases.

The main idea behind storing passwords in non-plaintext scheme is that
if an attacker gets access to your server, he can't easily just get
all users' passwords and start using them. With stronger schemes it
takes more time to crack the passwords.

Currently, the password schemes supported by \fBdovecotpw\fP are:
CRYPT MD5 MD5-CRYPT SHA SHA1 SMD5 SSHA PLAIN CLEARTEXT CRAM-MD5
HMAC-MD5 DIGEST-MD5 PLAIN-MD4 PLAIN-MD5 LDAP-MD5 LANMAN NTLM RPA.

\fBdovecotpw\fP  can be used to populate \fIdovecot\fR\|(1) password databases.
.SH OPTIONS
.TP
\fB-l\fP 
List known password schemes.
.TP
\fB-p <password>\fP 
Use <password> as the password to be encoded with the specified scheme. If this option is not used, you are prompted for one interactively.
.TP
\fB-s <scheme>\fP 
Specify the password scheme to be used to encrypt the password.  <scheme> must be one of the supported password scheme as listed here above. If you omit this option, the default scheme is used (HMAC-MD5).
.TP
\fB-u <user>\fP 
Specify the username. This can be needed by some schemes.
.TP
\fB-V\fP 
Internally verify the generated hash.
.SH AUTHOR
.TP
dovecotpw was written by Timo Sirainen <tss@iki.fi>.
.PP
This manual page was written by Xavier Lüthi <xavier@caroxav.be>,
for the Debian project (but may be used by others).
