.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "DOVECOT" "1" "4 August 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dovecot \- secure mail server that supports mbox and maildir mailboxes
.SH SYNOPSIS
\fBdovecot\fP [options]
.br
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBdovecot\fP is a mail server whose major goals are security and extreme
reliability. It tries very hard to handle all error conditions and verify that
all data is valid, making it nearly impossible to crash. It should also be
pretty fast, extensible, and portable.
.SH OPTIONS
.TP
\fB-F\fP Start dovecot as foreground process (otherwise: start as daemon)
.TP
\fB-p\fP Ask for private SSL key password
.TP
\fB-a\fP Dump configuration and exit
.TP
\fB-n\fP Dump all non-default configuration items and exit
.TP
\fB-c <config-file>\fP
Use <config-file> as path to the configuration instead of /usr/local/etc/dovecot.conf
.TP
\fB--version\fP Print version and exit
.TP
\fB--build-options\fP Print build options and exit
.TP
\fB--exec-mail <protocol> [<section>]\fP Start protocol from section
.SH AUTHOR
.TP
dovecot was written by Timo Sirainen <tss@iki.fi>.
.PP
This manual page was written by Fabio Tranchitella <kobold@debian.org>,
for the Debian project (but may be used by others).
