#!/bin/sh

set -e

if [ "$1" = "configure" -a -z "$2" ]; then
	# Add the imap option to the protocols line on first install
	sed -i -e '/^[[:space:]]*protocols *=/ {s/[[:space:]]*none//; /imap/!s/[[:space:]]*$/ imap/}' \
		/etc/dovecot/protocols.conf
fi

if [ -x "/etc/init.d/dovecot" ]; then
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d dovecot restart
	else
		/etc/init.d/dovecot restart
	fi
fi

#DEBHELPER#
