.TH dovecot 8 "June 2004"
.\" Copyright (c) 2004 Kai Hendry (hendry@iki.fi)
.SH NAME
dovecot \- An IMAP and POP3 mail server
.SH SYNOPSIS
.PP
.BI "dovecot [options]
.SH DESCRIPTION
.B dovecot
is a POP3 and IMAP mail server that can work with standard mbox and maildir 
formats.  It is fully compatible with UW-IMAP and Courier IMAP servers as 
well as mail clients accessing the mailboxes directly.
.PP
.B dovecot
can be setup to authenticate against LDAP, Postgres or MYSQL databases, but by 
default authentication is with 
.BR PAM(7)
.
.PP
.B dovecot
is normally started during the system boot, and runs as a background process
but it can also be run through
.BR inetd(8)
.
In the latter case, the
.B /usr/lib/dovecot/imap-login
or
.B /usr/lib/dovecot/pop3-login
binaries are run directly not
.B /usr/sbin/dovecot
.
.PP
.B dovecot
will log all of its activities according to syslog.
.SH OPTIONS
.TP 12
.BI \-c " \<config file\>"
This option changes the default configuration file in which 
.B dovecot 
looks for its configuration.
.
.TP 12
.BI \-F 
.B dovecot
will run in the foreground, and it will still log to syslog.
.TP
.BI \--version
Print version information and exits.

.SH FILES
.TP 12
.I /etc/dovecot/dovecot.conf
Default configuration file.
.TP 12
.I /etc/dovecot/dovecot-ldap.conf
Additional configuration for LDAP based authentication.
.TP 12
.I /etc/dovecot/dovecot-pgsql.conf
Additional configuration for Postgres based authentication.
.TP 12
.I /etc/dovecot/dovecot-mysql.conf
Additional configuration for MySQL based authentication.
.TP 12
.I /usr/lib/dovecot.
Location of 
.B dovecot 
modules.

.SH DEBIAN-SPECIFIC
.B dovecot
is split into three packages:
.IP "\(bu" 4
.B dovecot-common
contains files used by both servers
.IP "\(bu" 4
.B dovecot-imapd
contains the IMAP server
.IP "\(bu" 4
.B dovecot-pop3d
contains the POP3 server

.SH AUTHOR
Timo Sirainen <tss@iki.fi>

.SH COPYRIGHT AND LICENSE

Copyright (c) 2001-2002 Timo Sirainen

Dovecot is mostly licensed under the terms of the LGPL v2.1.  See the file 
COPYING in the source distribution for exceptions.

This man page is copyright (c) 2004 by Kai Hendry <hendry@iki.fi> who
wrote it for Debian GNU/Linux.  It may be freely used by others under
the terms of the BSD license.

.SH "SEE ALSO"
http://dovecot.org/

The mailing list:
http://dovecot.org/list/dovecot

