/* this file automatically generated by Makefile */
#include "lib.h"
#include "sql-api.h"
extern struct sql_db driver_pgsql_db;
extern struct sql_db driver_mysql_db;
extern struct sql_db driver_sqlite_db;
void sql_drivers_register_all(void) {
sql_driver_register(&driver_pgsql_db);
sql_driver_register(&driver_mysql_db);
sql_driver_register(&driver_sqlite_db);
}
